version: '3'
services:
  php-app:
    image: image_leuna
    ports:
      - "8080:80" # Port pour l'application PHP
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:management" # Interface de gestion de l'image officielle RabbitMQ
    ports:
      - "5672:5672" # Port AMQP(Advanced Message Queuing Protocol)
      - "15672:15672" # Port de l'interface de gestion de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

